### ISSUE TITLE
 System Tray icon?

### ISSUE THREAD

**Issue by dansdeals** [dale-roberts/MouseUnSnag#10]
This is just wonderful.
Is there any way to minimize the script to the System Tray icon?

**Comment by dale-roberts** [comment]
Thanks! Glad it is useful to you. Unfortunately I have not had time to work on this project myself, but I believe there have been a few forks of it, and it’s possible that one of the forks has already done this. Can see list of forks via the “Insights” tab at the top, then the Forks item in the menu on the left. Here is a direct link:


  *   https://github.com/dale-roberts/MouseUnSnag/network/members

dale

**Comment by drewnoakes** [comment]
@dandeals the code in PR #6 added a system tray icon.

Unfortunately this project seems dead and PRs are not being merged.

**Comment by patricknelson** [comment]
This is now available in the current 2.1 release available at https://github.com/MouseUnSnag/MouseUnSnag/releases. 

Thanks is due in no small part to your own contributions, @drewnoakes! Much appreciated for helping move that forward.
