### ISSUE TITLE
Allow to disable wrapping around screen?

### ISSUE THREAD

**Issue by alexysong** [dale-roberts/MouseUnSnag#12]
Most users are not used to that feature, myself included. 

I am getting this app to disable a sticky corner, because I am not used to that nonsense "feature" of ms. But the app introduce another "feature" which I am not used to either.

**Comment by drewnoakes** [comment]
I added this in #6. Unfortunately this project appears to have been abandoned.

**Comment by patricknelson** [comment]
Just as an FYI to the folks above, this project is still active and now lives at https://github.com/MouseUnSnag/MouseUnSnag. This feature is present via both GUI (right click on system tray icon) or via CLI flag at startup (`-w`). The ability to _retain_ this setting automatically on the next startup via just using GUI should hopefully be available in the next release v2.2 😄
