### ISSUE TITLE
How about "scale" instead of "clamp"?

### ISSUE THREAD

**Issue by yatyricky** [dale-roberts/MouseUnSnag#13]
![Untitled](https://user-images.githubusercontent.com/2650631/86219323-99f99700-bbb4-11ea-97e6-89598f872879.jpg)

and vice-versa

**Comment by sefodopo** [comment]
In my opinion, this is the only lacking feature of this project. So I went looking across forks to see if it has already been implemented and I found that FrancisBry already implemented this and it works well as far as I can tell in the few seconds that I have tried it so far.
https://github.com/FrancisBry/MouseUnSnag
