### ISSUE TITLE
Curser tp.

### ISSUE THREAD

**Issue by Snigismund** [dale-roberts/MouseUnSnag#17]
When i take my curser down from the top monitor  on the outmost left side it tp's my curser to the right side on my bottom moniter.

**Comment by patricknelson** [comment]
This is the old repo for Mouse Unsnag. Try https://github.com/MouseUnSnag/MouseUnSnag and see if it's still a problem and, if so, please open an issue there.

**Comment by dale-roberts** [comment]
Thanks Patrick. I've just made larger and bolder that initial "notice" about the new project on the landing page.
