### ISSUE TITLE
Mouse hook sometimes stops working

### ISSUE THREAD

**Issue by gillius** [dale-roberts/MouseUnSnag#5]
Sometimes the mouse hook stops working and even though application is still running, no events are received. The first time I noticed it is when leaving app running overnight. The second time was over lunch. The third time I didn't think I had locked screen or anything in between. I tried locking screen and switching user and it didn't reproduce the problem, so I am not yet sure of the trigger for the issue. If I figure out more I will update this issue.

**Comment by dale-roberts** [comment]
Thanks for reporting that. I believe I have noticed that also, usually after sleep/wake cycle, but not consistent. I will have to dig a bit to see what is up. I wonder if it is related to this problem/bug/feature where Windows will unhook a callback if it exceeds some execution time (could affect the WH_MOUSE_LL callback):


·        https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/56093d14-c1bc-4d0a-a915-57fef0695191/windows-7-setwindowshookex-callback-proc-stops-getting-called-after-exceeding-max-time-allowed?forum=windowsgeneraldevelopmentissues

It may be possible to switch from WH_MOUSE_LL to “Raw Input”

·        https://docs.microsoft.com/en-us/windows/desktop/inputdev/about-raw-input

I made a note to myself about this while I was developing the code, but I did not investigate whether that approach would give the information needed to make MouseUnSnag work. Maybe that time has come…

**Comment by gillius** [comment]
In my local copy of the tool, I deleted the Console.WriteLine whenever the mouse moves, with the thought that maybe that caused some delay that may trigger Windows to drop the hook. Since I tried it a couple days ago it hasn't happened again, but that can't prove entirely that it helps or solves the issue since I could never reliably reproduce the issue before.

**Comment by dale-roberts** [comment]
Jason, Thanks for the data point, that is good to know. I’ll also look into the option of avoiding the WH_MOUSE_LL callback, and using a different mechanism (“raw” input), though I don’t know if it would work the same way, or really do the job that is required.

**Comment by drewnoakes** [comment]
Console.WriteLine can be more expensive that you might think. It seems conceivable it'd trigger the OS to kick the handler out for running over budget.

**Comment by dale-roberts** [comment]
I believe you. I’ll have a look at the code. Probably best to disable the debug stuff unless it is “asked for”, maybe with an option. Of course, I find the debug info fascinating, but that probably does not translate to the general population...

**Comment by drewnoakes** [comment]
Calls to [`Debug.Write*`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.writeline?view=netframework-4.7.2#System_Diagnostics_Debug_WriteLine_System_String_
) are omitted by the compiler if you compile in release mode (via the `[Conditional("DEBUG")]` attribute). I also suspect they don't block the caller, unlike `Console.WriteLine` which flushes before returning (which is why selecting in a console pauses a console apps).

In Visual Studio this debug output appears in the output pane. As you're not using VS I'm not entirely sure where it goes, but if you want to see it we can add a console listener via the [`Listeners` property](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.listeners?view=netframework-4.7.2#System_Diagnostics_Debug_Listeners).

**Comment by gillius** [comment]
To be clear about what I did, I only removed the Console.WriteLine that takes places every single time that the mouse moves that outputs the mouse coordinates. I still left in the others, that display when monitors change or when the mouse jump is detected (I added the UnSnags to it actually so I can see how many times the tool has saved me from accidentally closing left monitor's maximized window when trying to click title bar of right monitor's maximized window). So far I've got an uptime around 72 hours on the same process.

**Comment by drewnoakes** [comment]
That makes sense. The mouse move handler shouldn't be doing any blocking IO.

Great to hear you've got 72 hours on the clock. Definitely sounds like that was the issue.

**Comment by patricknelson** [comment]
For what it's worth, I used to experience that same issue in this older version pretty regularly. My original hack was to just restart the app. 

However, the latest version v2.1 seems to  have been rock solid so far in the past >2 weeks that I've been using it. So far it has handled many sleep/hibernate cycles as well changes in display topology without issue (at least on my dual monitor setup connected to my laptop when plugged/unplugged). That version doesn't spawn a console window at all and uses an icon in the system tray instead. See the releases page at: https://github.com/MouseUnSnag/MouseUnSnag. I also have [a fork](https://github.com/patricknelson/MouseUnSnag/releases) that incorporates some newer [unreleased](https://github.com/MouseUnSnag/MouseUnSnag/pulls/patricknelson) (and [undocumented](https://github.com/MouseUnSnag/MouseUnSnag/issues/11) features) such as the ability to retain settings from the last startup, if you're interested.
